Repository BCSDLab/HANGANG_ANDROID, pull requests merged in 2021-07, with the labels that each got.

#28 Feature/fix review activity
  app/src/main/java/in/hangang/hangang/api/AuthApi.kt
  app/src/main/java/in/hangang/hangang/api/NoAuthApi.kt
  app/src/main/java/in/hangang/hangang/constant/ApiConstant.kt
  app/src/main/java/in/hangang/hangang/constant/SharedPreferenceConstant.kt
  app/src/main/java/in/hangang/hangang/data/entity/LectureTimeTable.kt
  app/src/main/java/in/hangang/hangang/data/source/LectureRepository.kt
  app/src/main/java/in/hangang/hangang/data/source/UserRepository.kt
  app/src/main/java/in/hangang/hangang/data/source/local/LectureLocalDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/local/UserLocalDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/remote/LectureRemoteDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/remote/UserRemoteDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/source/LectureDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/source/UserDataSource.kt
  app/src/main/java/in/hangang/hangang/di/ViewModelModule.kt
  app/src/main/java/in/hangang/hangang/ui/home/mytimetable/adapter/MyTimetableAdapter.kt
  app/src/main/java/in/hangang/hangang/ui/home/mytimetable/fragment/MyTimetableFragment.kt
  app/src/main/java/in/hangang/hangang/ui/home/mytimetable/viewmodel/MyTimetableFragmentViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/home/ranking/adapter/RankingListAdapter.kt
  app/src/main/java/in/hangang/hangang/ui/home/ranking/fragment/RankingListFragment.kt
  app/src/main/java/in/hangang/hangang/ui/home/recentlectures/fragment/RecentLecturesFragment.kt
  app/src/main/java/in/hangang/hangang/ui/home/recentlectures/viewmodel/RecentLecturesFragmentViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/home/recommendedlectures/fragment/RecommendedLecturesFragment.kt
  app/src/main/java/in/hangang/hangang/ui/home/recommendedlectures/viewmodel/RecommendedLecturesFragmentViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/activity/LectureEvaluationActivity.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/adapter/LectureClassTimeAdapter.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/fragment/LectureReviewDetailFragment.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/fragment/LectureReviewListFragment.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/viewmodel/LectureEvaluationViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/viewmodel/LectureReviewDetailViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/login/LoginActivity.kt
  app/src/main/java/in/hangang/hangang/ui/signup/activity/SignUpMajorActivity.kt
  app/src/main/res/drawable/selector_bookmark.xml
  app/src/main/res/layout/fragment_home_my_timetable.xml
  app/src/main/res/layout/fragment_lecture_review_detail.xml
  app/src/main/res/layout/item_home_my_timetable_list.xml
  app/src/main/res/layout/item_home_ranking_list.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
  core/src/main/res/drawable/ic_bookmark_blue.xml
  versions.gradle
Labels: enhancement

#50 Feature/fix main lecture docs adapter
  app/src/main/java/in/hangang/hangang/api/NoAuthApi.kt
  app/src/main/java/in/hangang/hangang/data/entity/email/Email.kt
  app/src/main/java/in/hangang/hangang/data/source/UserDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/local/UserLocalDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/remote/UserRemoteDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/repository/UserRepository.kt
  app/src/main/java/in/hangang/hangang/ui/home/HomeFragment.kt
  app/src/main/java/in/hangang/hangang/ui/home/recommendedlectures/fragment/RecommendedLecturesFragment.kt
  app/src/main/java/in/hangang/hangang/ui/lecturebank/fragment/LectureBankFragment.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/adapter/RecommendedDocsAdapter.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/fragment/LectureReviewDetailFragment.kt
  app/src/main/java/in/hangang/hangang/ui/signup/activity/SignUpActivity.kt
  app/src/main/java/in/hangang/hangang/ui/signup/activity/SignUpDocumentActivity.kt
  app/src/main/java/in/hangang/hangang/ui/signup/activity/SignUpEmailActivity.kt
  app/src/main/java/in/hangang/hangang/ui/signup/activity/SignUpMajorActivity.kt
  app/src/main/java/in/hangang/hangang/ui/signup/viewmodel/SignUpEmailViewModel.kt
  app/src/main/res/layout/activity_sign_up_email.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#64 Add function that timetable move to lecture-review-detail screen
  app/src/main/java/in/hangang/hangang/di/ViewModelModule.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/fragment/TimetableLectureDetailFragment.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/fragment/TimetableLectureListFragment.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/viewmodel/TimetableLectureDetailViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/viewmodel/TimetableLectureListViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/viewmodel/TimetableViewModel.kt
  app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#69 Added seasonal semester in timetable
  app/src/main/java/in/hangang/hangang/constant/TimetableConstant.kt
  app/src/main/java/in/hangang/hangang/data/entity/semester/Semester.kt
  app/src/main/java/in/hangang/hangang/data/entity/timetable/LectureTimeTable.kt
  app/src/main/java/in/hangang/hangang/data/source/TimeTableDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/local/TimeTableLocalDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/remote/TimeTableRemoteDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/repository/TimetableRepository.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/activity/TimetableAddActivity.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/fragment/TimetableFragment.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/viewmodel/TimetableAddActivityViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/viewmodel/TimetableLectureListViewModel.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/viewmodel/TimetableViewModel.kt
  app/src/main/java/in/hangang/hangang/util/DateUtil.kt
  app/src/main/java/in/hangang/hangang/util/SemesterUtil.kt
  app/src/main/res/layout/activity_timetable_add.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 강의자료

#73 Bugfix/fix timetable error
  app/src/main/java/in/hangang/hangang/ui/timetable/activity/TimetableListActivity.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/adapter/TimetableCustomLectureTimeAdapter.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/fragment/TimetableFragment.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/fragment/TimetableLectureDetailFragment.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/fragment/TimetableLectureListFragment.kt
  app/src/main/java/in/hangang/hangang/ui/timetable/viewmodel/TimetableViewModel.kt
  app/src/main/java/in/hangang/hangang/util/HangangDialogUtil.kt
  app/src/main/res/layout/item_timetable_lecture.xml
  app/src/main/res/values/strings.xml
Labels: bug, 시간표

#78 Add Hangang App logo
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#81 Hotfix/fix lecture review list view model
  app/src/main/java/in/hangang/hangang/ui/lecturereview/fragment/LectureReviewListFragment.kt
  app/src/main/java/in/hangang/hangang/ui/lecturereview/viewmodel/LectureReviewListViewModel.kt
Labels: bug

#83 Added hawk proguard rule
  app/proguard-rules.pro
Labels: bug

#88 Hotfix/solve design major sign up
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/in/hangang/hangang/data/request/SignUpRequest.kt
  app/src/main/java/in/hangang/hangang/data/source/UserDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/local/UserLocalDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/remote/UserRemoteDataSource.kt
  app/src/main/java/in/hangang/hangang/data/source/repository/UserRepository.kt
  app/src/main/java/in/hangang/hangang/ui/signup/activity/SignUpActivity.kt
  app/src/main/java/in/hangang/hangang/ui/signup/activity/SignUpEmailActivity.kt
  app/src/main/java/in/hangang/hangang/ui/signup/activity/SignUpMajorActivity.kt
  app/src/main/java/in/hangang/hangang/ui/signup/viewmodel/SignUpMajorViewModel.kt
  app/src/main/res/drawable/ic_hangang_google_play.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/values/strings.xml
Labels: bug

#92 Hotfix/fix lecture docs image size
  app/src/main/java/in/hangang/hangang/ui/lecturereview/activity/LectureEvaluationActivity.kt
  app/src/main/java/in/hangang/hangang/util/LectureReviewBindingAdapter.kt
  app/src/main/res/layout/activity_lecture_evaluation.xml
  app/src/main/res/layout/fragment_home_recommended_lectures.xml
  app/src/main/res/layout/fragment_lecture_review_detail.xml
  app/src/main/res/layout/item_recommended_lecture_docs.xml
  core/src/main/java/in/hangang/core/util/ViewExtension.kt
  core/src/main/res/values/colors.xml
Labels: bug

#93 Add auto login default settings
  app/src/main/java/in/hangang/hangang/ui/login/LoginActivity.kt
  app/src/main/java/in/hangang/hangang/ui/login/LoginViewModel.kt
Labels: bug
